version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: create_your_adventure_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: create_your_adventure_frontend_frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=/api
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
